## 基本配置
server:
  context-path: /demo
  version: 1.0
  name: demo
  undertow:
    worker-threads: 8 #默认io-threads * 8
#spring相关配置
spring:
  application:
    name: demo
  profiles:
    active: test
#统一格式
  jackson:
      date-format: yyyy-MM-dd #如果使用字符串表示，用这行设置格式
      timezone: GMT+8
      serialization:
        write-dates-as-timestamps: false #使用时间戳，使用数值timestamp表示日期


#swagger http://localhost:ip/swagger-ui.html#!
swagger:
  title: demo
  description: demo接口文档
  version: 1.0
  basePackage: com.ratel.demo.controller


ratel:
  exception:
    '1001': 参数异常！
    '2001': redis异常！
    '1000': {0}
